# Generated by Django 4.2.2 on 2023-06-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
